### ISSUE TITLE
swc support

### ISSUE THREAD

**Issue by bpierre** [fastpack/fastpack#152]
I was also wondering if there was any plan to support [swc](https://swc-project.github.io/) in the future?

**Comment by andreypopp** [comment]
I think it's possible already via webpack loaders support in fastpack. But having a direct integration without the need for node runtime would be nice indeed.

**Comment by andreypopp** [comment]
By the way, I see no Reason why swc should be faster than fastpack here.

**Comment by zindel** [comment]
@bpierre I love the SWC project! I had even some thoughts of re-writing the fastpack in Rust for better performance (not sure if I ever have enough time to do so :)) But, yeah, want to second what Andrey has said above: it seems swc provides the `swc-loader`, which should be usable right away with fastpack. If you try it – let me know how it goes. We'd happily add another test with it!

**Comment by dartess** [comment]
I decided to experiment a bit.
I took `preact`, `typescript`, `swc` (`swc-loader`), `fastpack` and connected it all...
It is worked! And it is amazing and impressive!

**Comment by zindel** [comment]
@dartess, thank you! Mind sharing the repo with your experiments if possible? And, I guess, I can officially close this one :)

**Comment by dartess** [comment]
@zindel 
https://github.com/dartess/preact-typescript-fastpack-swc

I hurried a little.

`swc` correctly converts `jsx` and `const` to the specified pragma and `var` in my code, but does not convert `const` from imports: 
```
\nconst _1_preact = __fastpack_require__(\"preact\");
```
Build [here](https://github.com/dartess/preact-typescript-fastpack-swc/blob/master/public/build/app.js).

It seems because of `\n`, but I'm not sure and I don't know whose responsibility it is, swc or fastpack.

In any case, I will be watching both projects and their updates! I hope for the appearance of the production mode.
